version: '3'
services:
  helios:
    container_name: helios
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - mysql

  mysql:
    user: "1000:50"
    container_name: helios-mysql
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'helios'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql-volume:/var/lib/mysql
